-- MySQL Script generated by MySQL Workbench
-- Sat May 28 15:16:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dob` VARCHAR(100) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `admin` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurants` (
  `restaurant_id` INT NOT NULL,
  `trade_name` VARCHAR(100) NOT NULL,
  `working_hours` VARCHAR(100) NOT NULL,
  `dining_room_capacity` INT NOT NULL,
  `drivethrough_availabilty` TINYINT NOT NULL,
  `delivery_availabilty` TINYINT NOT NULL,
  `reservation_availabilty` TINYINT NOT NULL,
  `big_chef` VARCHAR(45) NOT NULL,
  `support_all_diets` TINYINT NOT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branches` (
  `branch_id` INT NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `address` TEXT NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `opening_hours` VARCHAR(45) NOT NULL,
  `closing_hours` VARCHAR(45) NOT NULL,
  `restaurants_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `fk_branches_restaurants1_idx` (`restaurants_restaurant_id` ASC) ,
  CONSTRAINT `fk_branches_restaurants1`
    FOREIGN KEY (`restaurants_restaurant_id`)
    REFERENCES `mydb`.`restaurants` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviews_rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviews_rates` (
  `review_id` INT NOT NULL,
  `review_text` TEXT NULL,
  `rating_lvl` INT NULL,
  `users_id` INT NOT NULL,
  `branches_branch_id` INT NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_reviews_users1_idx` (`users_id` ASC) ,
  INDEX `fk_reviews_branches1_idx` (`branches_branch_id` ASC) ,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `mydb`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `users_user_id` INT NOT NULL,
  `restaurants_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`users_user_id`, `restaurants_restaurant_id`),
  INDEX `fk_users_has_restaurants_restaurants1_idx` (`restaurants_restaurant_id` ASC) ,
  INDEX `fk_users_has_restaurants_users1_idx` (`users_user_id` ASC) ,
  CONSTRAINT `fk_users_has_restaurants_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_restaurants_restaurants1`
    FOREIGN KEY (`restaurants_restaurant_id`)
    REFERENCES `mydb`.`restaurants` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id` INT NOT NULL,
  `image_url` VARCHAR(1000) NOT NULL,
  `restaurants_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `fk_images_restaurants1_idx` (`restaurants_restaurant_id` ASC) ,
  CONSTRAINT `fk_images_restaurants1`
    FOREIGN KEY (`restaurants_restaurant_id`)
    REFERENCES `mydb`.`restaurants` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
